config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      post "/answers" => 'answers#get'
    end
  end

  namespace :admin do
    root to: "answers#index"
    resources :answers
  end

  root to: 'client#index'

  get '/use_cases', to: 'client#use_cases'
end

app/controllers/client_controller.rb
class ClientController < ApplicationController
  
  def index
  end

  def use_cases
    @utterances = Answer.pluck(:utterances).flatten
  end

end

app/views/client/index.html.erb
<%= link_to 'Use Cases', use_cases_path %>
<%= link_to 'Employees', users_path %>
<%= link_to 'Questions', admin_answers_path %>
<div class="container positionChat">
  
  <div class="chatContainer">
    <div class="chatHead">
      ChatBot
    </div>
    <div class="chatHistory" id="chatHistory" data-url="<%= api_v1_answers_path %>">
      
      <div class="chatMessage">
        <img src="<%=image_url 'robot-design.png' %>" class="chatIcon" />
        Howdy, how can i help you?
      </div>

      <div id="chart" style="display:none;"><%= line_chart User.group_by_day(:created_at).count %></div>
    </div>
    <div class="input">
      <input type="text" name="text" id="inputText" placeholder="Ask your bot!" />
    </div>
  </div>
  <input id="authenticity_token" name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">

</div>

<script>
  
  $("#clearLS").on("click", function(){
    localStorage.removeItem("userId");
    window.location.reload();
  });

  var inputText = $("#inputText");

  function uuidv4() { // lifted from: https://stackoverflow.com/questions/105034/create-guid-uuid-in-javascript
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
      var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
      return v.toString(16);
    });
  }


  function userID(){
    var id = localStorage.getItem("userId");
    
    if(id === null){
      id = uuidv4();
      localStorage.setItem("userId", id);
    }

    $('#userID').html(id);

    return id;
  }

  function submit(){
    
    var text = inputText.val();
    inputText.attr('disabled', true).addClass('inactive').val("").attr('placeholder', "loading..");

    var template = '<div class="chatMessageUser"><span>'+text+'</span><img src="<%=image_url 'user.png' %>" class="chatIconUser" /></div>'
    $("#chatHistory").append(template);

    var resContainer = $("<div></div>");
    resContainer.addClass("chatMessage");
    resContainer.append('<img src="<%=image_url 'robot-design.png' %>" class="chatIcon" />');
    var restext = $("<span></span>");
    restext.html("...");
    resContainer.append(restext);
    $("#chatHistory").append(resContainer);

    var url = $('#chatHistory').attr("data-url");
    var at  = $('#authenticity_token').val();
    $.ajax({
      type: "POST",
      url: url,
      data: {
        "user_id": userID(),
        "text": text,
        "authenticity_token": at 
      },
      success: function(r){
        $("#chatHistory").animate({ scrollTop: $('#chatHistory').prop("scrollHeight")}, 300);
        if(text == 'show chart'){
          $('#chart').show()
        } else {
          restext.text(r.answer);
        }
      },
      error: function(r){
        restext.text(r.responseJSON.error);
      },
      complete: function(){
        inputText
          .removeAttr('disabled')
          .attr('placeholder', "Ask your bot!")
          .removeClass('inactive')
          .focus();
      }
    });

  }

  inputText.keyup(function(e){

    if (e.keyCode != 13){
      return true
    }

    submit();
  })

  $("#inputText").focus();
  userID();


</script>

app/views/client/use_cases.html.erb
<div class="container">
  
  <div class="utContainer">
    <h3>What can you talk about</h3>
    <div class="scrolly">
      <% @utterances.each do |u| %>
        <div class='ut'><%= u %></div>  
      <% end %>
    </div>
  </div>
</div>